### PR TITLE
ENCD-5829-allow-batch-download-from-more-dataset-pages

### PR DESCRIPTION
**Pull request by forresttanaka**
This involves both back- and front-end changes; back to allow those page types to download files, and front to enable those controls on those pages.

### CODE REVIEW

**Review by emro — DISMISSED** [review]
The code here looks good and it looks like it does what it's supposed to do. I have some feedback about the <FileGallery> component, and how the buttons look - I think the design could be a little more straightforward - but I'm not sure if this ticket is the place to address these thoughts, which I could put in Jira if that seems useful.

**Comment by forresttanaka** [comment]
@emro The design has issues specifically for these three new pages, or for the File Gallery panel in general?

**Comment by forresttanaka** [comment]
I now use the same criteria for the section download buttons as we’ve used for including files in dataset.files in dataset.py. This has also affected the experiment file galleries the same way but no one noticed, so hopefully this cleans it up for everything.

Also I fixed the bug with making too-long URLs to get contributing files.

**Comment by forresttanaka** [comment]
Updated https://encd-5829-datasets-dl-fytanaka.demo.encodedcc.org/ to this latest version and will launch a new clean demo for tomorrow.

**Review by emro — APPROVED** [review]
Everything looks good, code and demo.

**Pull request merged**
