### PR TITLE
ENCD-5239-fix-css-problem-on-examine-loci

### PR DESCRIPTION
**Pull request by zoldello**

### CODE REVIEW

**Review by emro — DISMISSED** [review]
Looks good!

**Comment by zoldello** [comment]
@emro Kline requested an additional change.

**Comment by zoldello** [comment]
@forresttanaka Do you have any issue with this commit:

https://github.com/ENCODE-DCC/encoded/pull/3318/commits/27be320fd87c1dc1881762fca0d9f8a6f3169cac

It makes text wrap in many add-pages like award and donor.

**Comment by zoldello** [comment]
> Would `word-break: break-word` do what you need? It at least works in Safari. Might have to just sacrifice IE.

@forresttanaka  Thanks for the catch. I  went with "word-break: break-all" despite the way it wraps words. "word-break: break-word" is deprecated and some sites say its non-standard.

**Review by emro — DISMISSED** [review]

**Comment by zoldello** [comment]
I rebased on origin/dev.

**Review by hitz — APPROVED** [review]
Appproved based on rebase/force push

**Pull request merged**
