### PR TITLE
2441 3505 ontology released

### PR DESCRIPTION
**Pull request by gabdank**
Moved "date released" audit from experiment to dataset
Added audit that checks the biosample term_id belongs to the corresponding ontology vocabulary (Venkat's)

### CODE REVIEW

**Comment by hitz** [comment]
I do not like the repetition of ontology_dict in 3 different audits.   It could either get put in a separate file (/audits/biosample_ontology.py?) or maybe in audits/__init__.py?  

This information is not needed outside audits, correct?  It's just  like an enhanced schema validation?

**Comment by gabdank** [comment]
I believe it is not needed outside the audits


On Dec 11, 2015, at 4:13 PM, Ben Hitz <notifications@github.com<mailto:notifications@github.com>> wrote:


I do not like the repetition of ontology_dict in 3 different audits. It could either get put in a separate file (/audits/biosample_ontology.py?) or maybe in audits/init.py?

This information is not needed outside audits, correct? It's just like an enhanced schema validation?

**Comment by gabdank** [comment]
excised ontology_dict and renamed
merged with branch 3472, now all in pull request  #1073

**Comment by hitz** [comment]
replaced by #1073

**Pull request closed without merging**
