### PR TITLE
Add some documentation for the advanced search

### PR DESCRIPTION
**Pull request by detrout**
Includes some discussion of how its implemented, some examples of how
to use it, and a link to more details of the search language syntax.

After the ENCODE Consortium meeting I learned there was a poorly documented advanced search syntax, I thought I'd add at least a little documentation

### CODE REVIEW

**Comment by hitz** [comment]
This is repeatedly failing the front end tests (behave).  I am not sure why.   Maybe merge in master?  Or you can run the test manually with: 
 bin/test -m bdd -v --splinter-webdriver chrome

**Comment by detrout** [comment]
How does adding a text file make the tests fail? I am confused....

I'll try to figure out, it'll just take me a bit to get a test environment working.

**Comment by hitz** [comment]
Yeah, perhaps just merge master into your branch?

**Comment by hitz** [comment]
No that makes no sense.... I bet for some reason sauce-labs doesn't like that it's your fork (wrong secret key or something) and is giving uninformative error message.
I think I know how to work around this; don't worry about it.

**Comment by hitz** [comment]
OK, I merge this manually with a deployment doc update and will submit PR to myself.

**Pull request closed without merging**
