### PR TITLE
ENCD-5401 Restrict batch download to certain types

### PR DESCRIPTION
**Pull request by forresttanaka**

### CODE REVIEW

**Review by hitz — DISMISSED** [review]

**Comment by forresttanaka** [comment]
Confirmed the CircleCI tests have passed, but show as failed here.

**Comment by hitz** [comment]
> Confirmed the CircleCI tests have passed, but show as failed here.

BDD looks like it failed on circle-ci when I clicked on Details so I restarted it...

**Comment by hitz** [comment]
Screen Shot 2020-07-15 at 5 42 41 PM

**Comment by forresttanaka** [comment]
Oh, it linked me to this test that appeared failed, so I restarted it and it passed. Now I realize it looks like it linked me to a dev CircleCI test, not mine. This is really confusing. I’ll see what the “new UI” for CircleCI is like.

**Review by hitz — APPROVED** [review]

**Pull request merged**
