### PR TITLE
SNO-86-escape-search-text

### PR DESCRIPTION
**Pull request by zoldello**

### CODE REVIEW

**Comment by zoldello** [comment]
@hitz  I fixed the merge conflict. Please, do not forget to go over to snovault-repo and check out the SNO-86-escape-search-text  codebase there, too.

**Comment by hitz** [comment]
I did clear the sno-86 PR though.

**Comment by zoldello** [comment]
@hitz Fixed now. I used the wrong "git add" command before

**Comment by zoldello** [comment]
@hitz Is there any more work you need me to do on this ticket? If not, please, approve this PR. Thanks.
Note- I rebased to fix a merge issue.

**Pull request merged**
