### PR TITLE
5151 Remove biodalliance login restriction

### PR DESCRIPTION
**Pull request by forresttanaka**
The back end controlled whether the Quick View button could render or not based on the user’s logged-in state, so the primary change happened in dataset.py which now doesn’t check the logged-in state before offering the Quick View data in the `visualize` calculated property.

search.js also checked the logged-in state to decide whether to draw the tabbed search results or not. This check was similarly removed so that it always displays when requested regardless of logged-in state.

### CODE REVIEW

**Comment by kilodalton** [comment]
@forresttanaka Please fix merge conflicts in `src/encoded/static/components/search.js`

**Comment by forresttanaka** [comment]
Conflict resolved, and tested in a demo.

**Comment by forresttanaka** [comment]
@kilodalton @hitz Conflict resolved, and tested in a demo.

**Comment by kilodalton** [comment]
Merged RM 5151

**Pull request merged**
