### PR TITLE
ENCD-4376 new ATAC-seq QC

### PR DESCRIPTION
**Pull request by yunhailuo**

### CODE REVIEW

**Comment by hitz** [comment]
There are some conflicts

**Comment by strattan** [comment]
I fixed all my changes that broke tests.  I also fixed the merge conflicts (I think) that came from the new RNA metrics already merged to dev.
So I think this is ready to merge.

**Comment by hitz** [comment]
Should we patch the demo?

**Comment by strattan** [comment]
Or launch a new one?  I did make a handful of changes, including adding a new attachment to an object.

**Pull request merged**
