### PR TITLE
ENCD-3287 (RM5050) replaced

### PR DESCRIPTION
**Pull request by gabdank**
All unaccessioned objects should not have status “replaced” as it is impossible to use alternate accessions redirections if you don’t have accession. So all the statuses lists that are not accessioned were updated to exclude replaced, and all the relevant replaced objects were upgraded to be deleted.

### CODE REVIEW

**Comment by kilodalton** [comment]
@gabdank Please address merge conflicts

**Comment by gabdank** [comment]
@kilodalton conflicts resolved

**Comment by kilodalton** [comment]
@gabdank I have restarted the tests several times for this branch on Travis. I think it is failing for legitimate test failures. I am starting a local test too which I will add here.

`git pull origin master`
`rm -rf develop`
`python3 bootstrap.py --buildout-version 2.4.1 --setuptools-version 18.5 && bin/buildout && bin/test -v -v --splinter-webdriver chrome && npm test;`

_Note:_ The develop step above is because snovault was updated.

**Comment by gabdank** [comment]
@kilodalton I am looking into it with local tests as well

**Comment by gabdank** [comment]
@kilodalton I pushed my fix, locally tests that used to fail now pass. but I haven't run all of them. let's wait for Travis's verdict

**Comment by gabdank** [comment]
@kilodalton except for python 2.7 I think it finally passes https://travis-ci.org/ENCODE-DCC/encoded/builds/248895703

**Comment by kilodalton** [comment]
Merged ENCD-3287 (RM5050)

**Pull request merged**
