### PR TITLE
REG-5166 change organoid color

### PR DESCRIPTION
**Pull request by emro**
Added another two colors so that "Organoid" and "Cell line" colors would not be the same on the matrix page.

### CODE REVIEW

**Comment by forresttanaka** [comment]
You’ll need to fix the datacolor-test.js test. It expected the colors to wrap around sooner.

**Review by forresttanaka — DISMISSED** [review]
OK, looks good! I’m glad the charts work out as well.

**Comment by emro** [comment]
I rebased last week, but no other changes have been made. @forresttanaka could you approve it again if it all still looks good?

**Review by forresttanaka — APPROVED** [review]
Still looks good

**Pull request merged**
