### PR TITLE
(WIP) 3277 matrix

### PR DESCRIPTION
**Pull request by davisagli**
This is a work in progress; opening a pull request so @nikhilRP can review the search view (`matrix` function at the bottom of search.py)

### CODE REVIEW

**Comment by hitz** [comment]
Should search.py be broken up?

**Comment by davisagli** [comment]
The matrix search uses a lot of the same helper functions as the plain search, so not necessarily.

**Comment by nikhilRP** [comment]
For another view I am currently working on, I re-organized search.py code and just imported helper functions. Either ways splitting it up shouldn't be a big task

**Comment by hitz** [comment]
not necessarily is a reasonable answer!  Also a search "superclass" (not explicitly) module makes sense as well.

**Comment by nikhilRP** [comment]
@davisagli I think the count in matrix should be linked for sure. I understand that there is no experiment facet for biosample_term_name, still having it more sense. Other wise code looks pretty code. 

eg: https://3277-matrix-0ccee27-davisagli.demo.encodedcc.org/search/?type=experiment&biosample_term_name=3134&assay_term_name=DNase-seq

**Comment by nikhilRP** [comment]
@hitz agreed

**Comment by davisagli** [comment]
@nikhilRP yeah I'll add links to the classic search results (and make sure filters with no facet are displayed in some way). I'm also planning to add the download/visualize buttons at the bottom of the matrix view.

**Comment by davisagli** [comment]
@hitz have you had a chance to play with this yet on the demo, and is this going in the right direction? http://3277-matrix-0ccee27-davisagli.demo.encodedcc.org/experiments/matrix

Please let me know which option I should pursue for dealing with large numbers of rows/columns: http://redmine.encodedcc.org/issues/3277#note-9

**Comment by hitz** [comment]
yeah, will get some comments out.  Obviously there are some styling issues.   I have just resurrected an assay "slim" (Grouping) branch.

**Comment by davisagli** [comment]
My todo list before this is ready:
- [ ] don't show 'Download' button if no results (example: https://3277-matrix-0ccee27-davisagli.demo.encodedcc.org/experiments/matrix?&target.investigated_as=transcription%20factor&replicates.library.biosample.donor.organism.scientific_name=Homo%20sapiens&organ_slims=blood%20vessel&searchTerm=skin)
- [ ] group result rows by biosample type and display each group with a header indicating the biosample type
- [ ] make "...and x more" labels show all results
- [ ] fix loading indicator
- [ ] make sure there's a way for users to navigate to the matrix search
- [ ] give user control over which facets are used for grouping (?)
- [ ] highlight active row/col
- [ ] any way to make tooltips on column headers work?
- [ ] tests for the matrix backend view
- [ ] basic browser test of loading the matrix, applying a filter, navigating to a cell
- [ ] rebase on master

**Pull request merged**
