### PR TITLE
3466 dataset breadcrumbs

### PR DESCRIPTION
**Pull request by forresttanaka**
Dataset pages with multi-word @type now break these into space-delimited words:

```
DATASETS / SUMMARY / MATCHEDSET                   => DATASETS / SUMMARY / MATCHED SET
DATASETS / SUMMARY / ORGANISMDEVELOPMENTSERIES    => DATASETS / SUMMARY / ORGANISM DEVELOPMENT SERIES
DATASETS / SUMMARY / REFERENCEEPIGENOME           => DATASETS / SUMMARY / REFERENCE EPIGENOME
DATASETS / SUMMARY / REPLICATIONTIMINGSERIES      => DATASETS / SUMMARY / REPLICATION TIMING SERIES
DATASETS / SUMMARY / TREATMENTCONCENTRATIONSERIES => DATASETS / SUMMARY / TREATMENT CONCENTRATION SERIES
DATASETS / SUMMARY / TREATMENTTIMESERIES          => DATASETS / SUMMARY / TREATMENT TIME SERIES
DATASETS / FILESET / UCSCBROWSERCOMPOSITE         => DATASETS / FILESET / UCSC BROWSER COMPOSITE
DATASETS / FILESET / PUBLICATIONDATA              => DATASETS / FILESET / PUBLICATION DATA
```

### CODE REVIEW

**Comment by hitz** [comment]
I don't like variables name id0 id1.    Kind of hesitant to hold back the merge on that regard... but take a look.

**Comment by forresttanaka** [comment]
Variable names changed to ```datasetType``` (the type of dataset — Series, FileSet) and ```filesetType``` and ```seriesType``` (the type of fileset and the type of series).

**Comment by hitz** [comment]
@forresttanaka has renamed, should request a new pull.

**Comment by hitz** [comment]
Oh wait I can re-open

**Comment by forresttanaka** [comment]
Did it close? I thought when updating a branch that’s been PRed, it just stayed open?

**Comment by forresttanaka** [comment]
Oh, @hitz closed it — never mind; I finally get it.

**Pull request merged**
