### PR TITLE
ENCD-5271-add-atac-dnase-output-types

### PR DESCRIPTION
**Pull request by bonitalam**

### CODE REVIEW

**Review by gabdank — DISMISSED** [review]
@bonitalam I think you can use an upgrade for file schema - to avoid the need to wrangle the update of enrichment files in DNase experiments later. You can change the output type of enrichment in DNase experiments only  to FDR cut rate, and leave any other enrichment file to be enrichment.

**Review by yunhailuo — DISMISSED** [review]

**Comment by bonitalam** [comment]
Just resolved the merge conflict

**Review by yunhailuo — DISMISSED** [review]

**Review by yunhailuo — APPROVED** [review]

**Comment by hitz** [comment]
Can someone clear this review?

**Comment by yunhailuo** [comment]
> @bonitalam I think you can use an upgrade for file schema - to avoid the need to wrangle the update of enrichment files in DNase experiments later. You can change the output type of enrichment in DNase experiments only to FDR cut rate, and leave any other enrichment file to be enrichment.

This is done.

**Review by gabdank — APPROVED** [review]

**Pull request merged**
