### PR TITLE
ENCD-4656 fix stupid bdd tests on travis

### PR DESCRIPTION
**Pull request by hitz**
pulling this to trigger travis

### CODE REVIEW

**Comment by forresttanaka** [comment]
There’s also this kind of line defined in browsersteps.py, though I don’t think I’ve ever used it and am not sure it helps:

```
@then(parse('I should see an element with the css selector "{css}" within {timeout:d} seconds'))
def should_see_element_with_css_within_timeout(browser, css, timeout):
    assert browser.is_element_present_by_css(css, wait_time=timeout), u'Element not found'
```

I don’t know what wait_time is by default.

**Comment by hitz** [comment]
Does that test fail often?

**Comment by forresttanaka** [comment]
The “I should see an element with the css selector…” is the kind of test you’re adding an extra three seconds before, so now that I see the version of the same test but with a delay, I wonder if that would work too.

**Comment by forresttanaka** [comment]
I’ll give that a try in another branch. I just got that CSS timeout error in a different place in the BDD test, in fact, a place I’d never seen it happen before.

**Comment by hitz** [comment]
yeah this one timed out waiting to load... maybe add a timeout here.?

**Comment by forresttanaka** [comment]
My (n=1) test went well until near the end when it timed out waiting for a form to load. I’m trying another experiment with changing the default timeout time. Travis started on that a few minutes ago #shootinginthedark

**Pull request closed without merging**
