### PR TITLE
ENCD-5185-fix-replication-type-for-pooled-clone-sequencing-experiments

### PR DESCRIPTION
**Pull request by yunhailuo**

### CODE REVIEW

**Review by gabdank — APPROVED** [review]

**Review by gabdank — CHANGES_REQUESTED** [review]
@yunhailuo can you please add a test that will ensure None is returned for pooled clone sequencing.

**Comment by yunhailuo** [comment]
> @yunhailuo can you please add a test that will ensure None is returned for pooled clone sequencing.

Good suggestion. Tests added.

**Review by gabdank — DISMISSED** [review]

**Comment by hitz** [comment]
*sigh* conflicts.

**Review by hitz — APPROVED** [review]
Approved after rebase+forcepush

**Pull request merged**
