### PR TITLE
ENCD-3839 Remove schemas for the deleted objects

### PR DESCRIPTION
**Pull request by keenangraham**
This removes mention of deleted objects (AntibodyApproval, Construct, CRISPR, RNAi, TALEN, TALEs, FastqcQualityMetric, ModificationTechnique) from codebase including: 
- audits
- schemas
- tests
- types
- upgrade
- loadxl.py
- static

### CODE REVIEW

**Comment by keenangraham** [comment]
> the function "test_upgrade_biosample_18_to_19" from checking "constructs" and "rnais", same comment for "test_upgrade_fly_worm_donor_7_8" in test_upgrade_donor.py

I think you are right. Removing to be consistent.

> Why in types/biosample.py you left "model_organism_constructs" on line 401?

Removed.

> There is a comment on "genetic_modifications"

Updated.

**Comment by gabdank** [comment]
@keenangraham I found reference to biosample.talens in 
encoded/src/encoded/static/build-server/renderer.js:
```
 39482          }
 39483:         var talenDocuments = [];
 39484:         if (biosample.talens && biosample.talens.length) {
 39485:             talenDocuments = biosample.talens.reduce(function (allDocs, talen) {
 39486:                 return talen.documents && talen.documents.length ? allDocs.concat(talen.documents) : allDocs;
 39487              }, []);
 39488          }

  117942:   // Display a stand-alone TALEN page.
 117943:    var TalenPage = function TalenPage(props) {
 117944         var context = props.context;
 117945:        var talen = (0, _objectutils.PanelLookup)({ context: context });
 117946         var itemClass = globals.itemClass(context, 'view-item');
 117947     
 117948:        var crumbs = [{ id: 'TALENs' }, { id: context.talen_platform, query: 'talen_platform=' + context.talen_platform, tip: context.talen_platform }];```

And some additional code about talens there, I think it should go

**Comment by gabdank** [comment]
in encoded/src/encoded/audit/biosample.py:
 ```
  228  function_dispatcher = {
  229:     'audit_constructs': audit_biosample_modifications,
```
may be the "audit_constructs" should be renamed to be "audit_modifications"

**Comment by gabdank** [comment]
in /Users/idan/Desktop/encoded/src/encoded/audit/experiment.py:
```

 3536:         'replicates.library.biosample.constructs',
 3537:         'replicates.library.biosample.constructs.target',
 3538:         'replicates.library.biosample.model_organism_donor_constructs',
 3539:         'replicates.library.biosample.model_organism_donor_constructs.target',

```
I think should be removed

**Comment by gabdank** [comment]
in /Users/idan/Desktop/encoded/src/encoded/static/build-server/renderer.js:
```

 39461: 	    var rnaiDocuments = [];
 39462: 	    if (biosample.rnais && biosample.rnais.length) {
 39463: 	        rnaiDocuments = biosample.rnais.reduce(function (allDocs, rnai) {
 39464: 	            return rnai.documents && rnai.documents.length ? allDocs.concat(rnai.documents) : allDocs;
 39465  	        }, []);
 39466  	    }
 .....
 39496  	    // Put together the document list for rendering
 39497  	    // Compile the document list
 39498: 	    var combinedDocuments = _underscore2.default.uniq([].concat(protocolDocuments, characterizations, constructDocuments, rnaiDocuments, donorDocuments, donorCharacterizations, donorConstructs, talenDocuments, treatmentDocuments));
```

should be cleaned up from RNAi on biosample

**Comment by keenangraham** [comment]
> @keenangraham I found reference to biosample.talens in
> encoded/src/encoded/static/build-server/renderer.js:

Are these outdated files built locally? On GitHub these are ignored:
screen shot 2018-03-09 at 1 52 10 pm

**Pull request merged**
