### PR TITLE
[HOLD] remove unused facet and column types from schemas

### PR DESCRIPTION
**Pull request by davisagli**
Remove `type` from definitions of facets and columns; it doesn't seem to be actually used anywhere.

### CODE REVIEW

**Comment by lrowe** [comment]
I'm going to hold off on merging this until the various schema changes we have in progress are merged. Too high a chance for merge conflicts right now.

**Comment by davisagli** [comment]
Fair enough. Let me know when those are done if you'd like me to update this.

**Comment by hitz** [comment]
David - can you reimplement this so that the changes will merge without conflicts?  There is no rush.

**Comment by davisagli** [comment]
@hitz I just updated this

**Pull request merged**
