### PR TITLE
ENCD-3387 (RM5200) fixing dataset linkTo in File.json

### PR DESCRIPTION
**Pull request by gabdank**
fixing in File.json the dataset linkTo property, it was a list without a real reason, so I turned it back into a single link instead.

### CODE REVIEW

**Comment by kilodalton** [comment]
@idan @aditin14 Please see the question on ENCD-3387 about the code change here

**Comment by gabdank** [comment]
@kilodalton the answer is no. When I modified the File.json in release 56  I started from list of different dataset types and ended up with one abstract Dataset in the list, the right thing to do was to stop using list , but I didn't - so I am fixing that now. File still can belong to only one Dataset - so no schema version change nor upgrades are needed.

**Comment by kilodalton** [comment]
@gabdank Thanks for the explanation. Typically a change to a pre-existing data object from an array to something that is not an array (or vice versa) needs extra changes. We'll go ahead based on your comments here.

**Comment by kilodalton** [comment]
Merged ENCD-3387 (RM5200)

**Pull request merged**
