### PR TITLE
678 aliases regex

### PR DESCRIPTION
**Pull request by estherc**
#678 tighter regex for aliases and upgrade for existing aliases

### CODE REVIEW

**Comment by hitz** [comment]
I think this travis BDD failure is not a bug in code or config.  I am going to run locally to be 100% sure.

**Comment by hitz** [comment]
passed locally, seems to have been a timing error on travis.ci.

**Comment by forresttanaka** [comment]
The Saucelabs video shows it failing either when displaying the file table I think, and other times failing when the edit form for an antibody took a _few minutes_ to come up, which was too long for Travis CI. None of this ever fails for me locally.

**Comment by kilodalton** [comment]
Merged RM 678

**Pull request merged**
